description: >
  rocker R image.
docker:
  - image: '<<parameters.image>>:<<parameters.version>>'
parameters:
  version:
    default: "4.0.4"
    description: >
      Pick a specific R version:
      https://hub.docker.com/_/r-base
    type: string
  image:
    default: "r-base"
    description: >
      Pick an image with R installed.
      Default is: https://hub.docker.com/_/r-base
    type: string

